db.regions.save({_id:"CHI", name:"Channel Islands", calc_level:true})
db.regions.save({_id:"EIRE", name:"Republic of Ireland", calc_level:true})
db.regions.save({_id:"ENG", name:"English", calc_level:false})
db.regions.save({_id:"MANX", name:"Isle of Man", calc_level:true})
db.regions.save({_id:"NI", name:"Northern Ireland", calc_level:true})
db.regions.save({_id:"SCO", name:"Scots", calc_level:false})
db.regions.save({_id:"WAL", name:"Welsh English", calc_level:true})

db.regions.save({_id:"ABN", name: "Aberdeen", parent_id: "NE_SCO", calc_level:false})
db.regions.save({_id:"ABR", name: "Aberystwtyh", parent_id: "WAL", calc_level:false})
db.regions.save({_id:"ASH", name: "Ashford", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"BATH", name: "Bath", parent_id: "CEN_SW_ENG", calc_level:false})
db.regions.save({_id:"BELF", name: "Belfast", parent_id: "NI", calc_level:false})
db.regions.save({_id:"BLKC", name: "Black Country", parent_id: "WMID_ENG", calc_level:false})
db.regions.save({_id:"BRAD", name: "Bradford", parent_id: "CEN_N_ENG", calc_level:false})
db.regions.save({_id:"BRGT", name: "Brighton", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"BRIS", name: "Bristol", parent_id: "CEN_SW_ENG", calc_level:false})
db.regions.save({_id:"BRNM", name: "Bournemouth", parent_id: "CEN_SW_ENG", calc_level:false})
db.regions.save({_id:"BRUM", name: "Birmingham", parent_id: "WMID_ENG", calc_level:false})
db.regions.save({_id:"CANT", name: "Canterbury", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"CAR", name: "Cardiff", parent_id: "SO_WAL", calc_level:false})
db.regions.save({_id:"CEN_ENG", name: "Central English", parent_id: "NOR_ENG", calc_level:false})
db.regions.save({_id:"CEN_LAN", name: "Central Lancashire", parent_id: "LN_ENG", calc_level:false})
db.regions.save({_id:"CEN_MID_ENG", name: "Central Midlands", parent_id: "EC_ENG", calc_level:false})
db.regions.save({_id:"CEN_N_ENG", name: "Central North English", parent_id: "LN_ENG", calc_level:false})
db.regions.save({_id:"CEN_SCO", name: "Central Scots", parent_id: "SCO", calc_level:false})
db.regions.save({_id:"CEN_SW_ENG", name: "Central Southwest English", parent_id: "SW_ENG", calc_level:false})
db.regions.save({_id:"CHE", name: "Cheshire", parent_id: "NWMID_ENG", calc_level:false})
db.regions.save({_id:"CHES", name: "Chester", parent_id: "CHE", calc_level:false})
db.regions.save({_id:"COR", name: "Cork", parent_id: "EIRE", calc_level:false})
db.regions.save({_id:"CORN", name: "Cornwall", parent_id: "LOW_SW_ENG", calc_level:false})
db.regions.save({_id:"COVN", name: "Coventry", parent_id: "WMID_ENG", calc_level:false})
db.regions.save({_id:"CUMB", name: "Cumbria", parent_id: "CEN_N_ENG", calc_level:false})
db.regions.save({_id:"DERB", name: "Derbyshire", parent_id: "NWMID_ENG", calc_level:false})
db.regions.save({_id:"DERRY", name: "Derry", parent_id: "NI", calc_level:false})
db.regions.save({_id:"DEV", name: "Devon", parent_id: "LOW_SW_ENG", calc_level:false})
db.regions.save({_id:"DON", name: "Donegal", parent_id: "EIRE", calc_level:false})
db.regions.save({_id:"DORS", name: "Dorset", parent_id: "LOW_SW_ENG", calc_level:false})
db.regions.save({_id:"DUB", name: "Dublin", parent_id: "EIRE", calc_level:false})
db.regions.save({_id:"DUND", name: "Dundee", parent_id: "ECN_SCO", calc_level:false})
db.regions.save({_id:"EA", name: "East Anglia", parent_id: "SE_ENG", calc_level:false})
db.regions.save({_id:"EA_ANG", name: "East Anglia", parent_id: "EA", calc_level:false})
db.regions.save({_id:"EC_ENG", name: "East Central English", parent_id: "CEN_ENG", calc_level:true})
db.regions.save({_id:"EC_SCO", name: "East Central Scots", parent_id: "CEN_SCO", calc_level:true})
db.regions.save({_id:"ECN_SCO", name: "East Central North Scots", parent_id: "CEN_SCO", calc_level:true})
db.regions.save({_id:"EDB", name: "Edinburgh", parent_id: "EC_SCO", calc_level:false})
db.regions.save({_id:"EKIL", name: "East Kilbride", parent_id: "WC_SCO", calc_level:false})
db.regions.save({_id:"ESX", name: "Essex", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"EXE", name: "Exeter", parent_id: "LOW_SW_ENG", calc_level:false})
db.regions.save({_id:"FALM", name: "Falmouth", parent_id: "LOW_SW_ENG", calc_level:false})
db.regions.save({_id:"GAL", name: "Galway", parent_id: "EIRE", calc_level:false})
db.regions.save({_id:"GLAS", name: "Glasgow", parent_id: "WC_SCO", calc_level:false})
db.regions.save({_id:"GLOS", name: "Gloucestershire", parent_id: "UPPER_SW_ENG", calc_level:false})
db.regions.save({_id:"GRIM", name: "Grimsby", parent_id: "NEMID_ENG", calc_level:false})
db.regions.save({_id:"GUER", name: "Guernsey", parent_id: "CHI", calc_level:false})
db.regions.save({_id:"HARR", name: "Harrogate", parent_id: "YRK", calc_level:false})
db.regions.save({_id:"HOME_C", name: "Home Counties", parent_id: "SE_ENG", calc_level:false})
db.regions.save({_id:"HULL", name: "Hull", parent_id: "YRK", calc_level:false})
db.regions.save({_id:"INV", name: "Inverness", parent_id: "NE_SCO", calc_level:false})
db.regions.save({_id:"IPS", name: "Ipswitch", parent_id: "EA", calc_level:false})
db.regions.save({_id:"ISLW", name: "Isle of Wight", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"KENT", name: "Kent", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"LANC", name: "Lancaster", parent_id: "CEN_N_ENG", calc_level:false})
db.regions.save({_id:"LEED", name: "Leeds", parent_id: "YRK", calc_level:false})
db.regions.save({_id:"LEIC", name: "Leicester", parent_id: "CEN_MID_ENG", calc_level:false})
db.regions.save({_id:"LIM", name: "Limerick", parent_id: "EIRE", calc_level:false})
db.regions.save({_id:"LINC", name: "Lincolnshire", parent_id: "NEMID_ENG", calc_level:false})
db.regions.save({_id:"LN_ENG", name: "Lower North English", parent_id: "NOR_ENG", calc_level:true})
db.regions.save({_id:"LOW_SW_ENG", name: "Lower Southwest English", parent_id: "SW_ENG", calc_level:false})
db.regions.save({_id:"LVP", name: "Liverpool", parent_id: "MERS", calc_level:false})
db.regions.save({_id:"MANC", name: "Manchester", parent_id: "NWMID_ENG", calc_level:false})
db.regions.save({_id:"MERS", name: "Merseyside", parent_id: "WC_ENG", calc_level:false})
db.regions.save({_id:"MID_ENG", name: "English Midlands", parent_id: "CEN_ENG", calc_level:false})
db.regions.save({_id:"MILK", name: "Milton Keynes", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"N_ENG", name: "North English", parent_id: "ENG", calc_level:false})
db.regions.save({_id:"NE_ENG", name: "Northeast England", parent_id: "NOR_ENG", calc_level:true})
db.regions.save({_id:"NE_SCO", name: "Northeast Scotland", parent_id: "NO_SCO", calc_level:true})
db.regions.save({_id:"NEMID_ENG", name: "Northeast Midlands", parent_id: "EC_ENG", calc_level:false})
db.regions.save({_id:"NEWC", name: "Newcastle", parent_id: "NE_ENG", calc_level:false})
db.regions.save({_id:"NHMP", name: "Northamptonshire", parent_id: "S_MID_ENG", calc_level:false})
db.regions.save({_id:"NO_SCO", name: "Northern Scots", parent_id: "SCO", calc_level:false})
db.regions.save({_id:"NOR_ENG", name: "Northern English", parent_id: "N_ENG", calc_level:false})
db.regions.save({_id:"NORW", name: "Norwich", parent_id: "EA", calc_level:false})
db.regions.save({_id:"NTHM", name: "Nottingham", parent_id: "CEN_MID_ENG", calc_level:false})
db.regions.save({_id:"NWMID_ENG", name: "Northwest Midlands", parent_id: "WC_ENG", calc_level:false})
db.regions.save({_id:"ORK", name: "Orkney", parent_id: "SCI", calc_level:false})
db.regions.save({_id:"OXF", name: "Oxford", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"POOL", name: "Poole", parent_id: "DORS", calc_level:false})
db.regions.save({_id:"PORT", name: "Portsmouth", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"PRES", name: "Preston", parent_id: "CEN_LAN", calc_level:false})
db.regions.save({_id:"RAMS", name: "Ramsgate", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"READ", name: "Reading", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"S_MID_ENG", name: "South Midlands", parent_id: "SE_ENG", calc_level:false})
db.regions.save({_id:"SCI", name: "Scottish Islands", parent_id: "SCO", calc_level:false})
db.regions.save({_id:"SE_ENG", name: "Southeast English", parent_id: "SO_ENG", calc_level:true})
db.regions.save({_id:"SE_IRE", name: "South East Ireland", parent_id: "EIRE", calc_level:false})
db.regions.save({_id:"SHEF", name: "Sheffield", parent_id: "YRK", calc_level:false})
db.regions.save({_id:"SHET", name: "Shetland", parent_id: "SCI", calc_level:false})
db.regions.save({_id:"SHROP", name: "Shropshire", parent_id: "NWMID_ENG", calc_level:false})
db.regions.save({_id:"SLI", name: "Sligo", parent_id: "EIRE", calc_level:false})
db.regions.save({_id:"SO_ENG", name: "South English", parent_id: "ENG", calc_level:false})
db.regions.save({_id:"SO_WAL", name: "South Wales", parent_id: "WAL", calc_level:false})
db.regions.save({_id:"SOUTH", name: "Southampton", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"STAN", name: "St Andrews", parent_id: "ECN_SCO", calc_level:false})
db.regions.save({_id:"SURY", name: "Surrey", parent_id: "HOME_C", calc_level:false})
db.regions.save({_id:"SW_ENG", name: "Southwest English", parent_id: "SO_ENG", calc_level:true})
db.regions.save({_id:"SWAN", name: "Swansea", parent_id: "SO_WAL", calc_level:false})
db.regions.save({_id:"SWIN", name: "Swindon", parent_id: "CEN_SW_ENG", calc_level:false})
db.regions.save({_id:"TEE", name: "Teeside", parent_id: "NE_ENG", calc_level:false})
db.regions.save({_id:"TYN", name: "Tyneside", parent_id: "NE_ENG", calc_level:false})
db.regions.save({_id:"UPPER_SW_ENG", name: "Upper Southwest English", parent_id: "SW_ENG", calc_level:false})
db.regions.save({_id:"WC_ENG", name: "West Central English", parent_id: "CEN_ENG", calc_level:true})
db.regions.save({_id:"WC_SCO", name: "West Central Scots", parent_id: "CEN_SCO", calc_level:true})
db.regions.save({_id:"WIG", name: "Wigan", parent_id: "NWMID_ENG", calc_level:false})
db.regions.save({_id:"WMID_ENG", name: "West Midlands", parent_id: "WC_ENG", calc_level:false})
db.regions.save({_id:"YORK", name: "York", parent_id: "YRK", calc_level:false})
db.regions.save({_id:"YRK", name: "Yorkshire", parent_id: "CEN_N_ENG", calc_level:false})
